# Generated by Django 3.1.3 on 2020-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201116_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.SmallIntegerField(choices=[(1, 'NOT_STARTED'), (2, 'PENDING'), (3, 'FINISHED'), (4, 'FAIL')], default=1, verbose_name='Статус задачи'),
        ),
    ]
