# Generated by Django 3.1.3 on 2020-11-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201116_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='word',
            field=models.CharField(default='', max_length=12, verbose_name='Слово'),
        ),
    ]
