# Generated by Django 3.1.3 on 2020-11-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='word',
            field=models.CharField(default='Python', max_length=12, verbose_name='Слово'),
        ),
    ]
